### PR TITLE
Update farm card design

### PR DESCRIPTION
**Pull request by acceleratedmonkey**
localhost_3000_ (2)

### CODE REVIEW

**Comment by etcd** [comment]
Just a small thing, if you could rename "Transactions History" to "Transaction History" :)

Also, if you change "source-code-pro" to be "Roboto Mono" (inside of GlobalStyle and src/index.css) you wouldn't need to put "Roboto Mono" in the styled divs that use it

Btw why is there both GlobalStyle and index.css?

**Comment by stablexyz** [comment]
Should change "Transactions History" to "Transaction History"

Also can centralize the monospace font style under GlobalStyle and src/index.css. Instead of including Roboto Mono in all the styled components, you can just change "font-family: source-code-pro, ..." to "font-family: Roboto Mono, ..."

What's the difference in function between GlobalStyle and index.css?

**Comment by stablexyz** [comment]
Two more things:

1. Should get rid of border between "Select" button and "Your Stake". I think you can do it this way:

In GenericCard:

```
const StyledLabelWrapper = styled.div`
  border-top: 1px solid rgb(118 69 217 / 0.2);
`
```

change to:

```
const StyledLabelWrapper = styled.div`
  border-top: 1px solid rgb(118 69 217 / 0.2);
  &:first-child {
    border-top: none;
  }
`
```

2. Get rid of margin/padding around the multiplier (x5, x3, x2, etc)

**Comment by acceleratedmonkey** [comment]
> What's the difference in function between GlobalStyle and index.css?
good questions 

looks like index.css actually not in used lol

**Comment by acceleratedmonkey** [comment]
localhost_3000_ (3)

**Comment by stablexyz** [comment]
Looks very good, thanks for the changes!

**Pull request merged**
